name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive # Scarica anche i temi se sono sottomoduli
          fetch-depth: 0        # Necessario se usi funzioni Hugo basate sulla cronologia Git

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' # Usa l'ultima versione disponibile (simile alla tua 0.160)
          extended: true         # Fondamentale per i temi moderni (SASS/SCSS)

      - name: Build
        run: |
          hugo --minify
          touch public/.nojekyll # Impedisce a GitHub di avviare Jekyll e rompere le date

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'MScaramuzzi'
          user_email: 'marco.scaramuzzi98@hotmail.it'
          commit_message: 'Deploy automatico: ${{ github.event.head_commit.message }}'
